# Install:
#     sudo pip install pre-commit
#
# Run manually on all files:
#     pre-commit run -a
#
# Install git hook to run automatically every time you attempt to commit:
#     pre-commit install
#
# To update this file:
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  # format code
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

  # remove unused imports
  - repo: https://github.com/hadialqattan/pycln
    rev: "v2.1.2"
    hooks:
      - id: pycln
        stages: [manual]

  # Check for spelling
  # Use tools/codespell_ignore_lines_from_errors.py
  # to rebuild .codespell-ignore-lines
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.2"
    hooks:
      - id: codespell
        exclude: xdot.py
